services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: reddit_user
      POSTGRES_PASSWORD: reddit_pass
      POSTGRES_DB: reddit_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reddit_user -d reddit_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5001:5000"
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://reddit_user:reddit_pass@postgres:5432/reddit_db

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend:5000

  # Optional: only enable if needed
  airflow:
    profiles: ["with-airflow"]
    build: ./airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://reddit_user:reddit_pass@postgres:5432/reddit_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      PYTHONPATH: /opt/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./backend:/opt/airflow/backend
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init \
               && airflow users create --username admin --password admin \
                    --firstname Admin --lastname User --role Admin --email admin@example.com \
               && exec airflow scheduler & exec airflow webserver"

volumes:
  pgdata: