version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: reddit_user
      POSTGRES_PASSWORD: reddit_pass
      POSTGRES_DB: reddit_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow:
    build: ./airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://reddit_user:reddit_pass@postgres:5432/reddit_db
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init \
               && airflow users create --username admin --password admin \
                    --firstname Admin --lastname User --role Admin --email admin@example.com \
               && exec airflow scheduler & exec airflow webserver"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    ports:
      - "5001:5000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"

volumes:
  pgdata:
