apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: reddit-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: scheduler
        image: gcr.io/cml-final-project/airflow:latest
        args: ["airflow", "scheduler"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: reddit-sentiment-secret
              key: DATABASE_URL
        volumeMounts:
        - name: airflow-config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg

      - name: webserver
        image: gcr.io/cml-final-project/airflow:latest
        args: ["airflow", "webserver"]
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: LocalExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              name: reddit-sentiment-secret
              key: DATABASE_URL
        volumeMounts:
        - name: airflow-config
          mountPath: /opt/airflow/airflow.cfg
          subPath: airflow.cfg

      volumes:
      - name: airflow-config
        configMap:
          name: reddit-sentiment-config
          items:
          - key: airflow.cfg
            path: airflow.cfg
