apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: reddit-sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/cml-final-project/backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: reddit-sentiment-secret
