apiVersion: v1
kind: ConfigMap
metadata:
  name: reddit-sentiment-config
  namespace: reddit-sentiment
data:
  airflow.cfg: |
    [core]
    executor = LocalExecutor
    sql_alchemy_conn = {{ .Env.DATABASE_URL }}
    load_examples = False

    [logging]
    logging_level = INFO
