apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: reddit-sentiment
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: reddit-sentiment-secret
              key: DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: reddit-sentiment-secret
              key: DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: reddit-sentiment-secret
              key: DB_NAME
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata   # Added accordingly
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/pgdata   # Updated path
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
