apiVersion: v1
kind: Secret
metadata:
  name: reddit-sentiment-secret
  namespace: reddit-sentiment
stringData:
  DB_USER:     reddit_user
  DB_PASSWORD: reddit_pass
  DB_NAME:     reddit_db
  DATABASE_URL: |
    postgresql+psycopg2://reddit_user:reddit_pass@postgres:5432/reddit_db
  REDDIT_CLIENT_ID:     your_client_id
  REDDIT_CLIENT_SECRET: your_client_secret
  REDDIT_USER_AGENT:    your_user_agent
